[package]
name = "project-x"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = "4.0.3"
async-graphql-actix-web = "4.0.3"
actix-web = { version = "4.1.0", features = ["macros"]}
slab = "0.4.2"
